spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://postgres:5432/postgres
    user: postgres
    password: postgres
    baseline-on-migrate: true
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: SMLOCALJWTOKEN